// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: gateway/v1/cache_service.proto

package cacheservice

import (
	proto "github.com/golang/protobuf/proto"
	model "github.com/pylonbot/pylon-gateway-protobuf-go/discord/v1/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetGuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGuildRequest) Reset() {
	*x = GetGuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildRequest) ProtoMessage() {}

func (x *GetGuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildRequest.ProtoReflect.Descriptor instead.
func (*GetGuildRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{0}
}

type GetGuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guild *model.GuildData `protobuf:"bytes,1,opt,name=guild,proto3" json:"guild,omitempty"`
}

func (x *GetGuildResponse) Reset() {
	*x = GetGuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildResponse) ProtoMessage() {}

func (x *GetGuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildResponse.ProtoReflect.Descriptor instead.
func (*GetGuildResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetGuildResponse) GetGuild() *model.GuildData {
	if x != nil {
		return x.Guild
	}
	return nil
}

type ListGuildChannelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGuildChannelsRequest) Reset() {
	*x = ListGuildChannelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildChannelsRequest) ProtoMessage() {}

func (x *ListGuildChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListGuildChannelsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{2}
}

type ListGuildChannelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*model.ChannelData `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
}

func (x *ListGuildChannelsResponse) Reset() {
	*x = ListGuildChannelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildChannelsResponse) ProtoMessage() {}

func (x *ListGuildChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListGuildChannelsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListGuildChannelsResponse) GetChannels() []*model.ChannelData {
	if x != nil {
		return x.Channels
	}
	return nil
}

type GetGuildChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId uint64 `protobuf:"fixed64,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *GetGuildChannelRequest) Reset() {
	*x = GetGuildChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildChannelRequest) ProtoMessage() {}

func (x *GetGuildChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildChannelRequest.ProtoReflect.Descriptor instead.
func (*GetGuildChannelRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetGuildChannelRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type GetGuildChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel *model.ChannelData `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *GetGuildChannelResponse) Reset() {
	*x = GetGuildChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildChannelResponse) ProtoMessage() {}

func (x *GetGuildChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildChannelResponse.ProtoReflect.Descriptor instead.
func (*GetGuildChannelResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetGuildChannelResponse) GetChannel() *model.ChannelData {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ListGuildMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	After uint64 `protobuf:"fixed64,1,opt,name=after,proto3" json:"after,omitempty"`
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListGuildMembersRequest) Reset() {
	*x = ListGuildMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildMembersRequest) ProtoMessage() {}

func (x *ListGuildMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildMembersRequest.ProtoReflect.Descriptor instead.
func (*ListGuildMembersRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListGuildMembersRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ListGuildMembersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListGuildMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*model.MemberData `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *ListGuildMembersResponse) Reset() {
	*x = ListGuildMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildMembersResponse) ProtoMessage() {}

func (x *ListGuildMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildMembersResponse.ProtoReflect.Descriptor instead.
func (*ListGuildMembersResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListGuildMembersResponse) GetMembers() []*model.MemberData {
	if x != nil {
		return x.Members
	}
	return nil
}

type GetGuildMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetGuildMemberRequest) Reset() {
	*x = GetGuildMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildMemberRequest) ProtoMessage() {}

func (x *GetGuildMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildMemberRequest.ProtoReflect.Descriptor instead.
func (*GetGuildMemberRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetGuildMemberRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetGuildMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *model.MemberData `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *GetGuildMemberResponse) Reset() {
	*x = GetGuildMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildMemberResponse) ProtoMessage() {}

func (x *GetGuildMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildMemberResponse.ProtoReflect.Descriptor instead.
func (*GetGuildMemberResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetGuildMemberResponse) GetMember() *model.MemberData {
	if x != nil {
		return x.Member
	}
	return nil
}

type ListGuildRolesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGuildRolesRequest) Reset() {
	*x = ListGuildRolesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildRolesRequest) ProtoMessage() {}

func (x *ListGuildRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildRolesRequest.ProtoReflect.Descriptor instead.
func (*ListGuildRolesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{10}
}

type ListGuildRolesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*model.RoleData `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *ListGuildRolesResponse) Reset() {
	*x = ListGuildRolesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildRolesResponse) ProtoMessage() {}

func (x *ListGuildRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildRolesResponse.ProtoReflect.Descriptor instead.
func (*ListGuildRolesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListGuildRolesResponse) GetRoles() []*model.RoleData {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetGuildRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"fixed64,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *GetGuildRoleRequest) Reset() {
	*x = GetGuildRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildRoleRequest) ProtoMessage() {}

func (x *GetGuildRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildRoleRequest.ProtoReflect.Descriptor instead.
func (*GetGuildRoleRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetGuildRoleRequest) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type GetGuildRoleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role *model.RoleData `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *GetGuildRoleResponse) Reset() {
	*x = GetGuildRoleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildRoleResponse) ProtoMessage() {}

func (x *GetGuildRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildRoleResponse.ProtoReflect.Descriptor instead.
func (*GetGuildRoleResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetGuildRoleResponse) GetRole() *model.RoleData {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListGuildEmojisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGuildEmojisRequest) Reset() {
	*x = ListGuildEmojisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildEmojisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildEmojisRequest) ProtoMessage() {}

func (x *ListGuildEmojisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildEmojisRequest.ProtoReflect.Descriptor instead.
func (*ListGuildEmojisRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{14}
}

type ListGuildEmojisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emojis []*model.EmojiData `protobuf:"bytes,1,rep,name=emojis,proto3" json:"emojis,omitempty"`
}

func (x *ListGuildEmojisResponse) Reset() {
	*x = ListGuildEmojisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildEmojisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildEmojisResponse) ProtoMessage() {}

func (x *ListGuildEmojisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildEmojisResponse.ProtoReflect.Descriptor instead.
func (*ListGuildEmojisResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListGuildEmojisResponse) GetEmojis() []*model.EmojiData {
	if x != nil {
		return x.Emojis
	}
	return nil
}

type GetGuildEmojiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmojiId uint64 `protobuf:"fixed64,1,opt,name=emoji_id,json=emojiId,proto3" json:"emoji_id,omitempty"`
}

func (x *GetGuildEmojiRequest) Reset() {
	*x = GetGuildEmojiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildEmojiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildEmojiRequest) ProtoMessage() {}

func (x *GetGuildEmojiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildEmojiRequest.ProtoReflect.Descriptor instead.
func (*GetGuildEmojiRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetGuildEmojiRequest) GetEmojiId() uint64 {
	if x != nil {
		return x.EmojiId
	}
	return 0
}

type GetGuildEmojiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emoji *model.EmojiData `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
}

func (x *GetGuildEmojiResponse) Reset() {
	*x = GetGuildEmojiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildEmojiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildEmojiResponse) ProtoMessage() {}

func (x *GetGuildEmojiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildEmojiResponse.ProtoReflect.Descriptor instead.
func (*GetGuildEmojiResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetGuildEmojiResponse) GetEmoji() *model.EmojiData {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *model.UserData `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserResponse) GetUser() *model.UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type GetGuildMemberVoiceStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetGuildMemberVoiceStateRequest) Reset() {
	*x = GetGuildMemberVoiceStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildMemberVoiceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildMemberVoiceStateRequest) ProtoMessage() {}

func (x *GetGuildMemberVoiceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildMemberVoiceStateRequest.ProtoReflect.Descriptor instead.
func (*GetGuildMemberVoiceStateRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetGuildMemberVoiceStateRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetGuildMemberVoiceStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoiceStateData *model.VoiceStateData `protobuf:"bytes,1,opt,name=voice_state_data,json=voiceStateData,proto3" json:"voice_state_data,omitempty"`
}

func (x *GetGuildMemberVoiceStateResponse) Reset() {
	*x = GetGuildMemberVoiceStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuildMemberVoiceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildMemberVoiceStateResponse) ProtoMessage() {}

func (x *GetGuildMemberVoiceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildMemberVoiceStateResponse.ProtoReflect.Descriptor instead.
func (*GetGuildMemberVoiceStateResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetGuildMemberVoiceStateResponse) GetVoiceStateData() *model.VoiceStateData {
	if x != nil {
		return x.VoiceStateData
	}
	return nil
}

type ListGuildChannelVoiceStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId uint64 `protobuf:"fixed64,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *ListGuildChannelVoiceStatesRequest) Reset() {
	*x = ListGuildChannelVoiceStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildChannelVoiceStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildChannelVoiceStatesRequest) ProtoMessage() {}

func (x *ListGuildChannelVoiceStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildChannelVoiceStatesRequest.ProtoReflect.Descriptor instead.
func (*ListGuildChannelVoiceStatesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{22}
}

func (x *ListGuildChannelVoiceStatesRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type ListGuildChannelVoiceStatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoiceStatesData []*model.VoiceStateData `protobuf:"bytes,1,rep,name=voice_states_data,json=voiceStatesData,proto3" json:"voice_states_data,omitempty"`
}

func (x *ListGuildChannelVoiceStatesResponse) Reset() {
	*x = ListGuildChannelVoiceStatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_cache_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGuildChannelVoiceStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildChannelVoiceStatesResponse) ProtoMessage() {}

func (x *ListGuildChannelVoiceStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_cache_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildChannelVoiceStatesResponse.ProtoReflect.Descriptor instead.
func (*ListGuildChannelVoiceStatesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_cache_service_proto_rawDescGZIP(), []int{23}
}

func (x *ListGuildChannelVoiceStatesResponse) GetVoiceStatesData() []*model.VoiceStateData {
	if x != nil {
		return x.VoiceStatesData
	}
	return nil
}

var File_gateway_v1_cache_service_proto protoreflect.FileDescriptor

var file_gateway_v1_cache_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1d, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x16, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37,
	0x0a, 0x05, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x05, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x73, 0x22, 0x3b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x42,
	0x02, 0x30, 0x01, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x58,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x79, 0x6c,
	0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x49, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x06, 0x42, 0x02, 0x30, 0x01, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x58, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x34, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x42, 0x02, 0x30, 0x01, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x50, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x79,
	0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x07, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x42, 0x02, 0x30, 0x01,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47,
	0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x54, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f,
	0x6a, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x65,
	0x6d, 0x6f, 0x6a, 0x69, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x79,
	0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06,
	0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x73, 0x22, 0x35, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x08, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06,
	0x42, 0x02, 0x30, 0x01, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x64, 0x22, 0x50, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45,
	0x6d, 0x6f, 0x6a, 0x69, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x22,
	0x2d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x06, 0x42, 0x02, 0x30, 0x01, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x34, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x42, 0x02, 0x30, 0x01, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x10, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x56,
	0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x47, 0x0a,
	0x22, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x42, 0x02, 0x30, 0x01, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x23, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x11, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e,
	0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x32, 0xb2, 0x0c, 0x0a, 0x0c, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x6b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x2e,
	0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f,
	0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x86, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x37, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x38,
	0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x80, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x35, 0x2e, 0x70,
	0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x83, 0x01, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x12, 0x36, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x7d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x34, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x70, 0x79, 0x6c, 0x6f,
	0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x7d, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x12, 0x34, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x77, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x32, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x80, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x73, 0x12, 0x35, 0x2e, 0x70,
	0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f,
	0x6a, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7a, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x12, 0x33, 0x2e, 0x70,
	0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x34, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x2d, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2e, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x9b, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3e,
	0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x6f, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f,
	0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x6f, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0xa4, 0x01, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x41, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x42, 0x2e, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x72, 0x0a, 0x27, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x79,
	0x6c, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x01, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x79, 0x6c, 0x6f, 0x6e, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d,
	0x67, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_gateway_v1_cache_service_proto_rawDescOnce sync.Once
	file_gateway_v1_cache_service_proto_rawDescData = file_gateway_v1_cache_service_proto_rawDesc
)

func file_gateway_v1_cache_service_proto_rawDescGZIP() []byte {
	file_gateway_v1_cache_service_proto_rawDescOnce.Do(func() {
		file_gateway_v1_cache_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_v1_cache_service_proto_rawDescData)
	})
	return file_gateway_v1_cache_service_proto_rawDescData
}

var file_gateway_v1_cache_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_gateway_v1_cache_service_proto_goTypes = []interface{}{
	(*GetGuildRequest)(nil),                     // 0: pylon.gateway.v1.cacheservice.GetGuildRequest
	(*GetGuildResponse)(nil),                    // 1: pylon.gateway.v1.cacheservice.GetGuildResponse
	(*ListGuildChannelsRequest)(nil),            // 2: pylon.gateway.v1.cacheservice.ListGuildChannelsRequest
	(*ListGuildChannelsResponse)(nil),           // 3: pylon.gateway.v1.cacheservice.ListGuildChannelsResponse
	(*GetGuildChannelRequest)(nil),              // 4: pylon.gateway.v1.cacheservice.GetGuildChannelRequest
	(*GetGuildChannelResponse)(nil),             // 5: pylon.gateway.v1.cacheservice.GetGuildChannelResponse
	(*ListGuildMembersRequest)(nil),             // 6: pylon.gateway.v1.cacheservice.ListGuildMembersRequest
	(*ListGuildMembersResponse)(nil),            // 7: pylon.gateway.v1.cacheservice.ListGuildMembersResponse
	(*GetGuildMemberRequest)(nil),               // 8: pylon.gateway.v1.cacheservice.GetGuildMemberRequest
	(*GetGuildMemberResponse)(nil),              // 9: pylon.gateway.v1.cacheservice.GetGuildMemberResponse
	(*ListGuildRolesRequest)(nil),               // 10: pylon.gateway.v1.cacheservice.ListGuildRolesRequest
	(*ListGuildRolesResponse)(nil),              // 11: pylon.gateway.v1.cacheservice.ListGuildRolesResponse
	(*GetGuildRoleRequest)(nil),                 // 12: pylon.gateway.v1.cacheservice.GetGuildRoleRequest
	(*GetGuildRoleResponse)(nil),                // 13: pylon.gateway.v1.cacheservice.GetGuildRoleResponse
	(*ListGuildEmojisRequest)(nil),              // 14: pylon.gateway.v1.cacheservice.ListGuildEmojisRequest
	(*ListGuildEmojisResponse)(nil),             // 15: pylon.gateway.v1.cacheservice.ListGuildEmojisResponse
	(*GetGuildEmojiRequest)(nil),                // 16: pylon.gateway.v1.cacheservice.GetGuildEmojiRequest
	(*GetGuildEmojiResponse)(nil),               // 17: pylon.gateway.v1.cacheservice.GetGuildEmojiResponse
	(*GetUserRequest)(nil),                      // 18: pylon.gateway.v1.cacheservice.GetUserRequest
	(*GetUserResponse)(nil),                     // 19: pylon.gateway.v1.cacheservice.GetUserResponse
	(*GetGuildMemberVoiceStateRequest)(nil),     // 20: pylon.gateway.v1.cacheservice.GetGuildMemberVoiceStateRequest
	(*GetGuildMemberVoiceStateResponse)(nil),    // 21: pylon.gateway.v1.cacheservice.GetGuildMemberVoiceStateResponse
	(*ListGuildChannelVoiceStatesRequest)(nil),  // 22: pylon.gateway.v1.cacheservice.ListGuildChannelVoiceStatesRequest
	(*ListGuildChannelVoiceStatesResponse)(nil), // 23: pylon.gateway.v1.cacheservice.ListGuildChannelVoiceStatesResponse
	(*model.GuildData)(nil),                     // 24: pylon.discord.v1.model.GuildData
	(*model.ChannelData)(nil),                   // 25: pylon.discord.v1.model.ChannelData
	(*model.MemberData)(nil),                    // 26: pylon.discord.v1.model.MemberData
	(*model.RoleData)(nil),                      // 27: pylon.discord.v1.model.RoleData
	(*model.EmojiData)(nil),                     // 28: pylon.discord.v1.model.EmojiData
	(*model.UserData)(nil),                      // 29: pylon.discord.v1.model.UserData
	(*model.VoiceStateData)(nil),                // 30: pylon.discord.v1.model.VoiceStateData
}
var file_gateway_v1_cache_service_proto_depIdxs = []int32{
	24, // 0: pylon.gateway.v1.cacheservice.GetGuildResponse.guild:type_name -> pylon.discord.v1.model.GuildData
	25, // 1: pylon.gateway.v1.cacheservice.ListGuildChannelsResponse.channels:type_name -> pylon.discord.v1.model.ChannelData
	25, // 2: pylon.gateway.v1.cacheservice.GetGuildChannelResponse.channel:type_name -> pylon.discord.v1.model.ChannelData
	26, // 3: pylon.gateway.v1.cacheservice.ListGuildMembersResponse.members:type_name -> pylon.discord.v1.model.MemberData
	26, // 4: pylon.gateway.v1.cacheservice.GetGuildMemberResponse.member:type_name -> pylon.discord.v1.model.MemberData
	27, // 5: pylon.gateway.v1.cacheservice.ListGuildRolesResponse.roles:type_name -> pylon.discord.v1.model.RoleData
	27, // 6: pylon.gateway.v1.cacheservice.GetGuildRoleResponse.role:type_name -> pylon.discord.v1.model.RoleData
	28, // 7: pylon.gateway.v1.cacheservice.ListGuildEmojisResponse.emojis:type_name -> pylon.discord.v1.model.EmojiData
	28, // 8: pylon.gateway.v1.cacheservice.GetGuildEmojiResponse.emoji:type_name -> pylon.discord.v1.model.EmojiData
	29, // 9: pylon.gateway.v1.cacheservice.GetUserResponse.user:type_name -> pylon.discord.v1.model.UserData
	30, // 10: pylon.gateway.v1.cacheservice.GetGuildMemberVoiceStateResponse.voice_state_data:type_name -> pylon.discord.v1.model.VoiceStateData
	30, // 11: pylon.gateway.v1.cacheservice.ListGuildChannelVoiceStatesResponse.voice_states_data:type_name -> pylon.discord.v1.model.VoiceStateData
	0,  // 12: pylon.gateway.v1.cacheservice.GatewayCache.GetGuild:input_type -> pylon.gateway.v1.cacheservice.GetGuildRequest
	2,  // 13: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildChannels:input_type -> pylon.gateway.v1.cacheservice.ListGuildChannelsRequest
	4,  // 14: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildChannel:input_type -> pylon.gateway.v1.cacheservice.GetGuildChannelRequest
	6,  // 15: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildMembers:input_type -> pylon.gateway.v1.cacheservice.ListGuildMembersRequest
	8,  // 16: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildMember:input_type -> pylon.gateway.v1.cacheservice.GetGuildMemberRequest
	10, // 17: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildRoles:input_type -> pylon.gateway.v1.cacheservice.ListGuildRolesRequest
	12, // 18: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildRole:input_type -> pylon.gateway.v1.cacheservice.GetGuildRoleRequest
	14, // 19: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildEmojis:input_type -> pylon.gateway.v1.cacheservice.ListGuildEmojisRequest
	16, // 20: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildEmoji:input_type -> pylon.gateway.v1.cacheservice.GetGuildEmojiRequest
	18, // 21: pylon.gateway.v1.cacheservice.GatewayCache.GetUser:input_type -> pylon.gateway.v1.cacheservice.GetUserRequest
	20, // 22: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildMemberVoiceState:input_type -> pylon.gateway.v1.cacheservice.GetGuildMemberVoiceStateRequest
	22, // 23: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildChannelVoiceStates:input_type -> pylon.gateway.v1.cacheservice.ListGuildChannelVoiceStatesRequest
	1,  // 24: pylon.gateway.v1.cacheservice.GatewayCache.GetGuild:output_type -> pylon.gateway.v1.cacheservice.GetGuildResponse
	3,  // 25: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildChannels:output_type -> pylon.gateway.v1.cacheservice.ListGuildChannelsResponse
	5,  // 26: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildChannel:output_type -> pylon.gateway.v1.cacheservice.GetGuildChannelResponse
	7,  // 27: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildMembers:output_type -> pylon.gateway.v1.cacheservice.ListGuildMembersResponse
	9,  // 28: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildMember:output_type -> pylon.gateway.v1.cacheservice.GetGuildMemberResponse
	11, // 29: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildRoles:output_type -> pylon.gateway.v1.cacheservice.ListGuildRolesResponse
	13, // 30: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildRole:output_type -> pylon.gateway.v1.cacheservice.GetGuildRoleResponse
	15, // 31: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildEmojis:output_type -> pylon.gateway.v1.cacheservice.ListGuildEmojisResponse
	17, // 32: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildEmoji:output_type -> pylon.gateway.v1.cacheservice.GetGuildEmojiResponse
	19, // 33: pylon.gateway.v1.cacheservice.GatewayCache.GetUser:output_type -> pylon.gateway.v1.cacheservice.GetUserResponse
	21, // 34: pylon.gateway.v1.cacheservice.GatewayCache.GetGuildMemberVoiceState:output_type -> pylon.gateway.v1.cacheservice.GetGuildMemberVoiceStateResponse
	23, // 35: pylon.gateway.v1.cacheservice.GatewayCache.ListGuildChannelVoiceStates:output_type -> pylon.gateway.v1.cacheservice.ListGuildChannelVoiceStatesResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gateway_v1_cache_service_proto_init() }
func file_gateway_v1_cache_service_proto_init() {
	if File_gateway_v1_cache_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_v1_cache_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildChannelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildChannelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildRolesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildRolesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildRoleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildEmojisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildEmojisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildEmojiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildEmojiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildMemberVoiceStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuildMemberVoiceStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildChannelVoiceStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_cache_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGuildChannelVoiceStatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_v1_cache_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_cache_service_proto_goTypes,
		DependencyIndexes: file_gateway_v1_cache_service_proto_depIdxs,
		MessageInfos:      file_gateway_v1_cache_service_proto_msgTypes,
	}.Build()
	File_gateway_v1_cache_service_proto = out.File
	file_gateway_v1_cache_service_proto_rawDesc = nil
	file_gateway_v1_cache_service_proto_goTypes = nil
	file_gateway_v1_cache_service_proto_depIdxs = nil
}
